### ISSUE TITLE
🐛 [BUG] antv5 项目中使用问题

### ISSUE THREAD

**Issue by Randysheng** [antvis/LarkMap#114]
### antv5 项目使用 LarkMap，遇到如下报错：
![image](https://user-images.githubusercontent.com/11868294/205227868-92fc4337-1ebe-4bce-ac7c-9c4d431c2bf0.png)

使用版本：
![image](https://user-images.githubusercontent.com/11868294/205228467-2c49ca3c-2e57-4f53-8ebf-05479816c974.png)

**Comment by lvisei** [comment]
@Randysheng LarkMap 里面依赖 Antd 4 的一些组件，4 与 5 样式不兼容的，现在还不支持，后面排期会做脱离依赖 antd 组件
