### ISSUE TITLE
🐛 [BUG]ChoroplethLayer图层点击事件：页面图层选择失效，但是数据有 

### ISSUE THREAD

**Issue by websybin** [antvis/LarkMap#157]
![image](https://user-images.githubusercontent.com/84109842/223348753-62457395-2037-4b5f-bc4e-10964821b084.png)
![image](https://user-images.githubusercontent.com/84109842/223348801-735125c2-e50f-4f2e-8253-d5c6caf31438.png)

**Comment by lvisei** [comment]
什么选择失效 @websybin

**Comment by lvisei** [comment]
setState 之后，父组件会更新，图层组件会走 diff，只有图层的属性没有改变，图层就不会更新，也就不会失去选择状态。属性判断改变的逻辑有例外，比如 source，不会做深度对比，成本较高，写代码时尽量不生成新的对象；还有就是函数属性，做不了 diff，使用的时候 useMemo 控制好这些变量。

如果进行上述优化，还是有更新丢失状态情况，codesanbox 复现

**Comment by lvisei** [comment]
setState 之后，父组件会更新，图层组件会走 diff，只有图层的属性没有改变，图层就不会更新，也就不会失去选择状态。属性判断改变的逻辑有例外，比如 source，不会做深度对比，成本较高，写代码时尽量不生成新的对象；还有就是函数属性，做不了 diff，使用的时候 useMemo 控制好这些变量。

如果进行上述优化，还是有更新丢失状态情况，codesanbox 复现
