### ISSUE TITLE
🐛 [BUG] RasterLayer 销毁时报错，暂不确实是不是所有Layer

### ISSUE THREAD

**Issue by SaltFish001** [antvis/LarkMap#196]
[Uploading 127.0.0.1-1700796210267.log…]()
[192.168.80.104-1700793832035.log](https://github.com/antvis/LarkMap/files/13454675/192.168.80.104-1700793832035.log)

### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [LarkMap](https://codesandbox.io/s/larkmap-issue-template-c9m1hr) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]

- **LarkMap Version**:
    "@antv/larkmap": "^1.4.6",
- **Platform**:
   x86-64

**Comment by SaltFish001** [comment]
该问题仅在React18下复现，react17暂无

**Comment by SaltFish001** [comment]
ImageLayer 图片上下镜像翻转

**Comment by lvisei** [comment]
@SaltFish001 升级 L7 依赖到最新即可
