### ISSUE TITLE
🐛 [BUG]地图为百度地图时，缩放等级不一致

### ISSUE THREAD

**Issue by jiasy1616** [antvis/LarkMap#205]
初始config的zoom等级设置为4，但zoom控件上显示为3，与底图为高德地图时等级差1
同时，初始的zoom等级只支持整数，小数会被自动取整

- **LarkMap Version**:1.4.11
- **Platform**:

**Comment by heiyexing** [comment]
是 L7 的问题，已经反馈过去了
