### ISSUE TITLE
🥰 [FEATURE]LayerSwitchControl组件的poper没有按主题色渲染

### ISSUE THREAD

**Issue by Dreammy23** [antvis/LarkMap#207]
### 💻 Features description [Please make everyone to understand it]
图层显隐组件在任何主题色下弹出框的颜色都是白色，希望可以按主题色渲染

### 🏞 What problem does this feature solve
现状
![image](https://github.com/antvis/LarkMap/assets/18047832/888b88fc-bdf3-409a-887a-870e47c260cb)

预期
当前图标图层是暗色，popper的内容区域也应该为黑色

**Comment by heiyexing** [comment]
图层显隐的控件原本背景色就是写死的   如果需要自行覆盖成暗色的话   可以通过 popup 的 class 自行覆盖
