### ISSUE TITLE
🐛 [BUG] 官网的钉钉群二维码已失效

### ISSUE THREAD

**Issue by cnafan** [antvis/LarkMap#209]
### 🐛 Bug description 
官网的钉钉群二维码已失效
https://larkmap.antv.antgroup.com/guide/faq
![image](https://github.com/antvis/LarkMap/assets/9312901/d66dbe4e-9767-4b36-ad55-ee2461a56af8)

### 📷 Step to reproduce
https://larkmap.antv.antgroup.com/guide/faq

### 🏞 Expected result
修复二维码链接

### 🚑 Any additional [like screenshots]
- **LarkMap Version**:"1.4.13"
- **Platform**:win

**Comment by heiyexing** [comment]
https://github.com/antvis/LarkMap/pull/210
