### ISSUE TITLE
🐛 [BUG] LayerPopup控制台提示报错

### ISSUE THREAD

**Issue by hsp-sz** [antvis/LarkMap#211]
### 🐛 Bug description [Please make everyone to understand it]
![image](https://github.com/antvis/LarkMap/assets/60083015/ec102657-177d-4015-aea2-2b37c06f2a2a)

> Please provide a link by forking these links [LarkMap](https://codesandbox.io/s/larkmap-issue-template-c9m1hr) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]

- **LarkMap Version**:
- **Platform**:

**Comment by heiyexing** [comment]
和 https://github.com/antvis/LarkMap/issues/192 问题一致，统一修复
