### ISSUE TITLE
🐛 [BUG]ChoroplethLayer中文本的位置不太正常

### ISSUE THREAD

**Issue by hsp-sz** [antvis/LarkMap#212]
### 🐛 Bug description [Please make everyone to understand it]
缩略之后，名字文本都跑到了边界线了。再看看山东省的，直接跑到海里面了
<img width="1033" alt="image" src="https://github.com/antvis/LarkMap/assets/60083015/648e9f45-f67a-4796-a1c8-5d2695d87f72">

> Please provide a link by forking these links [LarkMap](https://codesandbox.io/s/larkmap-issue-template-c9m1hr) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]

- **LarkMap Version**:
- **Platform**:

**Comment by lvisei** [comment]
可自行指定行政的经纬度点

![image](https://github.com/antvis/LarkMap/assets/26923747/b339d75c-f91d-4e31-84f2-fa3469a54907)

https://larkmap.antv.antgroup.com/components/layers/composite-layers/choropleth-layer#labelposition

**Comment by hsp-sz** [comment]
> 可自行指定行政的经纬度点
> 
> ![image](https://private-user-images.githubusercontent.com/26923747/301066523-b339d75c-f91d-4e31-84f2-fa3469a54907.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDMyNDMsIm5iZiI6MTcwNjg0Mjk0MywicGF0aCI6Ii8yNjkyMzc0Ny8zMDEwNjY1MjMtYjMzOWQ3NWMtZjkxZC00ZTMxLTg0ZjItZmEzNDY5YTU0OTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDAzMDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0Y2RhMmY1NGQ4OTFlZTgzN2M0ZmQwNjEzNWE1MzE5MGY1ZGU1NDM1MDIyZTU5OWYyNTBmYjAyZmM1NzgzYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1T9SmQRBJq7dD5mWu_6ah5UZ9ZokN7HT5pYQ5xOZTwo)
> 
> https://larkmap.antv.antgroup.com/components/layers/composite-layers/choropleth-layer#labelposition

问题是这个描述写的 默认几何中心点，你们这个默认几何中心点算得也不对啊。我这个issue提的意思不是说让我去指定，而是让你们去修复这个算的不正确的中心点。

**Comment by lvisei** [comment]
对于不规则的多边形，几何中心点，自然不在中心，靠计算都不理想，比如河北，包围了北京，中心点都跑北京了，比如甘肃省，都跑外面去了，广东省的范围有沿海地区，中心点自动不在陆地，山东有海上小岛等等。行政省会点位的标记，按照地图制图合格性来说，行政名称必须标记实际的行政地理点位。对于合格行政地图的绘制，都是数据里面带有行政点位的，不是靠计算得来的。

**Comment by hsp-sz** [comment]
![image](https://github.com/antvis/LarkMap/assets/60083015/4e547497-4242-4cf6-a1b5-50ccf0529e7b)
这个也合理是吗？

**Comment by lhw-888** [comment]
解决了吗，老铁
