### ISSUE TITLE
🐛 [BUG]LegendCategories的labels数据一致时控制台key报错

### ISSUE THREAD

**Issue by hsp-sz** [antvis/LarkMap#213]
### 🐛 Bug description [Please make everyone to understand it]
![image](https://github.com/antvis/LarkMap/assets/60083015/0dd5a83f-8a85-48a2-9164-c8280b416b8c)

> Please provide a link by forking these links [LarkMap](https://codesandbox.io/s/larkmap-issue-template-c9m1hr) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**:

### 🏞 Expected result
key应该拿label+color，参考l7plot，支持重复label，不会报错
<img width="1066" alt="image" src="https://github.com/antvis/LarkMap/assets/60083015/de153417-bc7f-45e7-a957-a2a6ed0b8c10">

### 🚑 Any additional [like screenshots]

- **LarkMap Version**:
- **Platform**:

**Comment by lvisei** [comment]
@hsp-sz 这个好改，来贡献代码吧～
