### ISSUE TITLE
🐛 [BUG] useDraw的shape，在切换形状后导致无法绘制

### ISSUE THREAD

**Issue by hsp-sz** [antvis/LarkMap#222]
### 🐛 Bug description [Please make everyone to understand it]
<img width="737" alt="image" src="https://github.com/antvis/LarkMap/assets/60083015/3301d531-a6d0-4e1c-b714-8f82e4a09494">

https://codesandbox.io/p/sandbox/wizardly-thompson-cnlvkp?file=%2FApp.tsx%3A19%2C16

> Please provide a link by forking these links [LarkMap](https://codesandbox.io/s/larkmap-issue-template-c9m1hr) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]

- **LarkMap Version**:
- **Platform**:

**Comment by lvisei** [comment]
升级 L7 至 2.21.3 以上
