### ISSUE TITLE
🐛 [BUG] ChoroplethLayer-lable-position，Not at the geometric center point

### ISSUE THREAD

**Issue by baihuayao** [antvis/LarkMap#227]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [LarkMap](https://codesandbox.io/s/larkmap-issue-template-c9m1hr) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**: [Link](https://codesandbox.io/p/sandbox/compassionate-einstein-9yh847)

### 🚑 Any additional [like screenshots]

- **LarkMap Version**: 1.4.13
- **Platform**: react 16

**Comment by lvisei** [comment]
可自行数据映射指定 lable  经纬度位置，https://larkmap.antv.antgroup.com/components/layers/composite-layers/choropleth-layer#labelposition

**Comment by baihuayao** [comment]
> 可自行数据映射指定 lable 经纬度位置，https://larkmap.antv.antgroup.com/components/layers/composite-layers/choropleth-layer#labelposition
> 
> 
> 可自行数据映射指定标签深度位置

**invalid**
[Link](https://codesandbox.io/p/sandbox/compassionate-einstein-9yh847?file=%2FApp.tsx%3A23%2C50)

config
`label: {
  field: "name",
  position: { coordinates: "centroid" }
}`

**Comment by lvisei** [comment]
需要将数据转化为 json 数据

![image](https://github.com/antvis/LarkMap/assets/26923747/ea1fb0a8-c0e7-4924-8afd-f557b6d68daa)

**Comment by baihuayao** [comment]
> 需要将数据转化为 json 数据
> 
> ![image](https://private-user-images.githubusercontent.com/26923747/336015736-ea1fb0a8-c0e7-4924-8afd-f557b6d68daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzEzMTcsIm5iZiI6MTcxNzQ3MTAxNywicGF0aCI6Ii8yNjkyMzc0Ny8zMzYwMTU3MzYtZWExZmIwYTgtYzBlNy00OTI0LThhZmQtZjU1N2I2ZDY4ZGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDAzMTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MDc5NmNjNTUwMzIwMmRjNDk4ZWQxODFlYzhlZTI3YjMwYTZlODI3YzI3NWNiNzc0NWVmYTdjNTRjM2NiMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7gGlMHAiFuhuFW43kZAALASIxQLXvwRkp2VksmJazIs)

is json
![WX20240604-114440](https://github.com/antvis/LarkMap/assets/16205030/c7c60d00-d5f6-464f-8068-b344fc77ccca)

**Comment by lvisei** [comment]
这是 geojson 数据，https://l7.antv.antgroup.com/api/source/json#%E9%9D%A2%E6%95%B0%E6%8D%AE
![image](https://github.com/antvis/LarkMap/assets/26923747/fb0dd68a-d162-4580-9e86-b7763a7499d5)
