### ISSUE TITLE
🤔 [QUESTION]

### ISSUE THREAD

**Issue by CanonLs** [antvis/LarkMap#237]
### 🐛 Question description [Please make everyone to understand it]
为什么  scene.on('loaded', () => {console.log("????"); }); 根本不执行呢？
还是说有其他用法啊  很简单的例子 我没有办法让loaded监听事件执行下去 谁来帮帮我 谢谢
```typescript
const mapInstance = new TencentMap({
    center: [105, 29.732983],
    // token: '你申请的 Key',
    zoom: 3.2,
    pitch: 30,
    baseMap: { type: "satellite", features: ["base", "road"] }
});

const MapSence = () => {
    const scene = useScene();
    useEffect(() => {
        scene.on('loaded', () => {
            console.log("????");
        });
    }, []);

    return null;
};

const Map = () => {

    return <LarkMap id="container" map={mapInstance} style={{ height: '100%', width: "100%" }} onSceneLoaded={(scene) => { }} >
        <MapSence></MapSence>
    </LarkMap>;
};
export default Map;
``` 
### 💻 Link to minimal reproduction

Please provide a link by forking these links [LarkMap](https://codesandbox.io/s/larkmap-issue-template-c9m1hr) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

- **LarkMap Version**:
- **Platform**:

**Comment by lvisei** [comment]
useScene() 拿到的 scene 已经是 loaded 完成
