### ISSUE TITLE
🤔 [QUESTION]  如何使用高德地图实例上的api呢  没找到

### ISSUE THREAD

**Issue by haobarry** [antvis/LarkMap#244]
### 🐛 Question description [Please make everyone to understand it]

使用了高德地图,然后拿到的map实例好像不是高德的 上面没有高德js api上的方法

比如我现在想使用 map.setLimitBounds();
限制下地图显示范围

### 🚑 Any additional [like screenshots]

- **LarkMap Version**: 最新的
- **Platform**:windows

**Comment by lvisei** [comment]
https://github.com/antvis/L7/issues/2618#issuecomment-2413004443
