### ISSUE TITLE
提供统一的事件绑定方案

### ISSUE THREAD

**Issue by wangxingkang** [antvis/LarkMap#26]
https://github.com/pansyjs/larkmap  已实现，觉得可以的话 我提个PR

**Comment by lvisei** [comment]
@wangxingkang 怎么使用的，贴个使用说明？

**Comment by wangxingkang** [comment]
@lvisei  

示例 

https://larkmap.xingkang.wang/components/lark-map#%E4%BA%8B%E4%BB%B6%E7%BB%91%E5%AE%9A  

核心代码

https://github.com/pansyjs/larkmap/blob/master/src/hooks/useEvents.ts

**Comment by lvisei** [comment]
可以的，这个需求必须有，不过实现思路可以再讨论一下，留个 DingDing ?

**Comment by wangxingkang** [comment]
wangxingkang1314

**Comment by lvisei** [comment]
https://github.com/visgl/react-map-gl/blob/master/src/mapbox/mapbox.ts#L576-L584

这样会可能会简洁一点
